<script lang="ts">
	import { addMessages, init, getLocaleFromNavigator, t } from 'svelte-intl-precompile';
	// @ts-expect-error - !! file auto generated by build toolchain
	import en from '$locales/en.js';
	// import nl from '$locales/nl.js';
	addMessages('en', en);
	// addMessages('nl', nl);

	init({
		fallbackLocale: 'en',
		initialLocale: getLocaleFromNavigator('en') ?? undefined
	});

	import axios from 'axios';
	import { Env } from '../env';
	import { discord } from '../stores/discord';

	// TODO: deprecate the axios interface, move to sveltekit fetch instead
	if (!browser) {
		const baseUrl = Env.public()['PUBLIC_BASE_URL'];
		axios.defaults.baseURL = baseUrl;
	}

	export let data: LayoutData;

	onMount(async () => {
		// TODO: handle authentication check gracefully using server loads
		if (browser) {
			axios.get('/api/auth/discord/authenticated').then(async (response) => {
				const authenticated = response.data.authenticated;

				if (authenticated) {
					// Returns an encrypted session cookie to identify the user
					const user = await axios.get('/api/auth/discord/user');

					discord.update(user.data);

					osu.fetch();
				}
			});
		}
	});

	import '../app.scss';

	import Modal from 'svelte-simple-modal';
	import { onMount } from 'svelte';
	import { browser } from '$app/environment';
	import { osu } from '../stores/osu';
	import { modal } from '../stores/modal';
	import type { LayoutData } from './$types';
	import Cookies from './cookies.svelte';
</script>

<svelte:head>
	<title>Endless Mirage — Your one stop shop for GFX & Collabs</title>
</svelte:head>

<!-- svelte-ignore a11y-missing-attribute -->
<div id="background">
	<div class="decoration" id="left">
		<img src="/assets/decoration.svg" />
		<div class="overlay" />
	</div>
	<div class="decoration" id="right">
		<img src="/assets/decoration.svg" />
		<div class="overlay" />
	</div>
</div>

<slot />

{#if data.cookies_accepted === undefined}
	<Cookies />
{/if}

{#if browser}
	<Modal
		show={$modal}
		styleWindow={{ background: '#773632' }}
		styleContent={{
			height: '100%'
		}}
		closeButton={false}
	/>
{/if}

<style lang="scss">
	#background {
		position: fixed;
		background: $content-background;

		top: 0;

		width: 100%;
		height: 100%;

		z-index: -3;

		img {
			height: 100%;
			opacity: 0.03;
			position: relative;
			z-index: -2;
		}

		.decoration {
			position: fixed;
			height: 100%;

			.overlay {
				position: absolute;
				top: 0;
				left: 0;
				height: 100%;
				width: 100%;
				z-index: -1;
			}
		}

		#left {
			left: 0;

			.overlay {
				background: linear-gradient(
					90deg,
					rgba($content-background, 0) 0%,
					$content-background 80%
				);
			}
		}

		#right {
			right: 0;

			.overlay {
				background: linear-gradient(
					270deg,
					rgba($content-background, 0) 0%,
					$content-background 80%
				);
			}
		}
	}
</style>
