<script>
	import { addMessages, init, getLocaleFromNavigator } from 'svelte-intl-precompile';
	// @ts-expect-error - !! file auto generated by build toolchain
	import en from '$locales/en.js';
	// @ts-expect-error - !! file auto generated by build toolchain
	import nl from '$locales/nl.js';
	addMessages('en', en);
	addMessages('nl', nl);

	init({
		fallbackLocale: 'en',
		// @ts-ignore - !! type returns null but expects undefined instead
		initialLocale: getLocaleFromNavigator('en')
	});

	import '../app.scss';
</script>

<slot />
