<script>
	import { addMessages, init, getLocaleFromNavigator } from 'svelte-intl-precompile';
	// @ts-expect-error - !! file auto generated by build toolchain
	import en from '$locales/en.js';
	// @ts-expect-error - !! file auto generated by build toolchain
	import nl from '$locales/nl.js';
	addMessages('en', en);
	addMessages('nl', nl);

	init({
		fallbackLocale: 'en',
		// @ts-ignore - !! type returns null but expects undefined instead
		initialLocale: getLocaleFromNavigator('en')
	});

	import axios from 'axios';
	import { Env } from '../env';
	import { discord } from '../stores/discord';

	if (!browser) {
		const baseUrl = Env.public()['PUBLIC_BASE_URL'];
		axios.defaults.baseURL = baseUrl;
	}

	onMount(async () => {
		axios.get('/api/discord/authenticated').then(async (response) => {
			const authenticated = response.data.authenticated;

			if (authenticated) {
				// Returns an encrypted session cookie to identify the user
				const user = await axios.get('/api/discord/user');

				discord.update(user.data);
			}
		});
	});

	import '../app.scss';

	import Header from '../components/generic/header/header.svelte';
	import { onMount } from 'svelte';
	import { browser } from '$app/env';
</script>

<svelte:head>
	<title>Endless Mirage — Your one stop shop for GFX & Collabs</title>
</svelte:head>

<Header />
<div id="background" />

<div id="content">
	<slot />
</div>

<style lang="scss">
	#content {
		display: flex;
		justify-content: center;

		left: 0;
		right: 0;

		bottom: 0;

		width: 100%;
		min-height: 100%;
	}

	#background {
		position: fixed;
		background: $content-background;

		top: 0;

		width: 100%;
		height: 100%;

		z-index: -1;
	}
</style>
