<script>
	import { addMessages, init, getLocaleFromNavigator } from 'svelte-intl-precompile';
	// @ts-expect-error - !! file auto generated by build toolchain
	import en from '$locales/en.js';
	// @ts-expect-error - !! file auto generated by build toolchain
	import nl from '$locales/nl.js';
	addMessages('en', en);
	addMessages('nl', nl);

	init({
		fallbackLocale: 'en',
		// @ts-ignore - !! type returns null but expects undefined instead
		initialLocale: getLocaleFromNavigator('en')
	});

	import axios from 'axios';
	import { discord } from '../stores/discord';

	onMount(async () => {
		axios.get('/api/discord/authenticated').then(async (response) => {
			const authenticated = response.data.authenticated;

			if (authenticated) {
				const user = await axios.get('/api/discord/user');

				discord.update(user.data);
			}
		});
	});

	import '../app.scss';

	import Header from '../components/generic/header/header.svelte';
	import { onMount } from 'svelte';
</script>

<svelte:head>
	<title>Endless Mirage — Your one stop shop for GFX & Collabs</title>
</svelte:head>

<div id="body">
	<Header />
	<div id="background">
		<div id="content">
			<slot />
		</div>
	</div>
</div>

<style lang="scss">
	#body {
		display: flex;
		justify-content: center;
		align-items: center;
		flex-direction: column;

		position: absolute;
		top: 0;
		left: 0;
		right: 0;
		bottom: 0;

		// helps with dev tools
		z-index: -2;

		height: 100%;
	}

	#content {
		max-width: $max-width;
		width: 100%;
	}

	#background {
		background: $content-background;
		width: 100%;
		height: 100%;

		z-index: -1;

		display: flex;
		justify-content: center;
	}
</style>
